<?php

namespace sportogether\Bundle\Repository;

/**
 * azRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class azRepository extends \Doctrine\ORM\EntityRepository
{
}
