<?php

namespace sportogether\Bundle\Repository;

/**
 * datetimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class datetimeRepository extends \Doctrine\ORM\EntityRepository
{
}
