<?php

namespace sportogether\Bundle\Repository;

/**
 * rencontrePublicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rencontrePublicRepository extends \Doctrine\ORM\EntityRepository
{
}
